[package]
name = "mal_sql_backup"
version = "0.1.0"
authors = ["Max Leonhardt <m.leonhardt424@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
scraper = "0.12.0"

[dependencies.reqwest]
version = "0.10.6"
features = ["blocking"]
